### ISSUE TITLE
Modif makefile

### ISSUE THREAD

**Issue by mavax74** [mavax74/Projet-1-Informatique-aleatoire#1]
Il faudrait modifier le makefile pour que celui ci soit dans le dossier mère et pas dans src, comme ça je pourrai aller récup les fichiers du corpus directement sans m'emmerder, et sauver les modèles dedans au passage.

**Comment by Schwingg** [comment]
pas compris ???
tu veux que l'executable soit deplacer a un endroit ?
je te le deplace dans le dossier mere

**Comment by Schwingg** [comment]
si tu fait make all ca va le compiler puis le deplacer  a la racine du dossier du pojet

**Comment by mavax74** [comment]
super merci !

**Comment by Schwingg** [comment]
de rien
