### ISSUE TITLE
segfault a l'execution

### ISSUE THREAD

**Issue by Schwingg** [mavax74/Projet-1-Informatique-aleatoire#2]
j'obtien un segfault lors de l'execution du programme et ce peux importe l'option (u ou b) utilise

 ./projet -u ../corpus/french.txt

**Comment by Schwingg** [comment]
l'erreur est lors du printf de la ligne 56 de Cree_modele_unigramme.c

est lors du printf ligne 58  de Cree_modele_bigramme.c

**Comment by mavax74** [comment]
Ca marche quand je le lance depuis /src en mettant french.txt dedans avec ./projet -u french.txt, et ça seg fault quand je fais un make all et que je le lance depuis ../ avec ./projet -u corpus/french.txt, donc ça doit etre un probleme de chemin lors de l'ouverture ou de la création du fichier, j 'y jetterai un oeil demain. Et les morceaux que j ai mis compilent, mais je ne les ai pas encore testés, je verrai ça un plus tard, mais dans tous les cas on est pas partis pour être en retard j'ai l'impression.
Bon vikend !

**Comment by mavax74** [comment]
Trop bien, y'a même un smiley feu d'artifice, on arrete pas le progres

**Comment by Schwingg** [comment]
ta craque mec

bon je vais faire un peu de rapport si j'ai le courage

**Comment by mavax74** [comment]
c'est bon, c'était un probleme de gestion des noms de fichiers, je l'ai résolu en créant une macro CORPUS_FOLDER qui vaut "corpus/", donc maintenant il faut appeler le fichier depuis le répertoire mère, et sans le path corpus, comme ça ./projet -u french.txt ; la gestion de collection de modèle commence à marcher à peu près, mais c'est un vrai champ de mines du coup la semaine prochaine je refactoriserai un gros coup pour y voir plus clair, et je debuggerai le truc comme il faut.

**Comment by Schwingg** [comment]
ok super merci
